# Generated by Django 4.1.5 on 2023-01-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_delete_potho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='anchor',
            new_name='author',
        ),
    ]
